### ISSUE TITLE
HDNode.derivePath broken?

### ISSUE THREAD

**Issue by mariusk** [christroutner/bch-js#56]
I get an error message about function being undefined. Inside the actual source code of HDNode's class definition inside `hdnode.js`, there's this nugget:
```javascript
derivePath(hdnode, path) {
    return hdnode.derivePath(path)
  }
```
Assuming `hdnode` it an instance of the same class, this would effectively mean we're trying to call `"somePath".derivePath()`, which fails for obvious reasons.

**Comment by christroutner** [comment]
Hi, I'm in the process of deprecating this repository in favor of this one:
https://github.com/Permissionless-Software-Foundation/bch-js

Can you please file this issue over there? Sorry for the confusion.

Also, can you add a link to the code library you're trying to point out? The snippet is hard to analyze because I don't have the rest of the code around it to see as context.

**Comment by mariusk** [comment]
Done, thanks.
